env:
  OCI_TENANCY_OCID: "${OCI_TENANCY_OCID}"
  OCI_USER_OCID: "${OCI_USER_OCID}"
  OCI_FINGERPRINT: "${OCI_FINGERPRINT}"
  OCI_PRIVATE_KEY_PATH: "${OCI_PRIVATE_KEY_PATH}"
  OCI_REGION: "af-johannesburg-1"

